# Generated by Django 6.0.4 on 2026-05-01 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_ar', models.CharField(max_length=300)),
                ('title_ku', models.CharField(max_length=300)),
                ('location_en', models.CharField(max_length=200)),
                ('location_ar', models.CharField(max_length=200)),
                ('location_ku', models.CharField(max_length=200)),
                ('type_en', models.CharField(default='Full-time', max_length=100)),
                ('type_ar', models.CharField(default='دوام كامل', max_length=100)),
                ('type_ku', models.CharField(default='تەواو وەقت', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('closes_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_en', models.CharField(max_length=300)),
                ('caption_ar', models.CharField(max_length=300)),
                ('caption_ku', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=300)),
                ('title_ar', models.CharField(max_length=300)),
                ('title_ku', models.CharField(max_length=300)),
                ('excerpt_en', models.TextField()),
                ('excerpt_ar', models.TextField()),
                ('excerpt_ku', models.TextField()),
                ('content_en', models.TextField(blank=True)),
                ('content_ar', models.TextField(blank=True)),
                ('content_ku', models.TextField(blank=True)),
                ('tag_en', models.CharField(max_length=100)),
                ('tag_ar', models.CharField(max_length=100)),
                ('tag_ku', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='news/')),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('governorate', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('education_level', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portfolio.career')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
