# Generated by Django 6.0.4 on 2026-05-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-created_at'], 'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='career',
            name='closes_at',
            field=models.DateField(blank=True, null=True, verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='career',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='career',
            name='location_ar',
            field=models.CharField(max_length=200, verbose_name='Location (Arabic)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='location_en',
            field=models.CharField(max_length=200, verbose_name='Location (English)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='location_ku',
            field=models.CharField(max_length=200, verbose_name='Location (Kurdish)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='career',
            name='title_ar',
            field=models.CharField(max_length=300, verbose_name='Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='title_en',
            field=models.CharField(max_length=300, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='title_ku',
            field=models.CharField(max_length=300, verbose_name='Title (Kurdish)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='type_ar',
            field=models.CharField(default='دوام كامل', max_length=100, verbose_name='Type (Arabic)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='type_en',
            field=models.CharField(default='Full-time', max_length=100, verbose_name='Type (English)'),
        ),
        migrations.AlterField(
            model_name='career',
            name='type_ku',
            field=models.CharField(default='تەواو وەقت', max_length=100, verbose_name='Type (Kurdish)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption_ar',
            field=models.CharField(max_length=300, verbose_name='Caption (Arabic)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption_en',
            field=models.CharField(max_length=300, verbose_name='Caption (English)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption_ku',
            field=models.CharField(max_length=300, verbose_name='Caption (Kurdish)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Applied At'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portfolio.career', verbose_name='Career'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(upload_to='cvs/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='education_level',
            field=models.CharField(max_length=100, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='governorate',
            field=models.CharField(max_length=100, verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='mobile',
            field=models.CharField(max_length=30, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ar',
            field=models.TextField(blank=True, verbose_name='Content (Arabic)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Content (English)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ku',
            field=models.TextField(blank=True, verbose_name='Content (Kurdish)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt_ar',
            field=models.TextField(verbose_name='Excerpt (Arabic)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt_en',
            field=models.TextField(verbose_name='Excerpt (English)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt_ku',
            field=models.TextField(verbose_name='Excerpt (Kurdish)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag_ar',
            field=models.CharField(max_length=100, verbose_name='Tag (Arabic)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag_en',
            field=models.CharField(max_length=100, verbose_name='Tag (English)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag_ku',
            field=models.CharField(max_length=100, verbose_name='Tag (Kurdish)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=300, verbose_name='Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=300, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ku',
            field=models.CharField(max_length=300, verbose_name='Title (Kurdish)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
